export const SCHEDULING_RULES = {
  MAX_THEORY_PERIODS_PER_DAY: 5,
  MAX_LABS_TUTORIALS_PER_DAY: 2,
  LAB_DURATION_HOURS: 2,
  TUTORIAL_DURATION_HOURS: 1,
  THEORY_DURATION_HOURS: 1,
  MIN_HOURS_BETWEEN_SAME_SUBJECT: 1,
  MAX_SLOTS_PER_DAY: 8, // 8 slots per day (9:00 AM to 5:00 PM)
} as const; 